### GET All users + address + profile
GET http://localhost:8080/users

### GET user by ID
GET http://localhost:8080/users/18

### GET All Products
GET http://localhost:8080/products

### GET Products by category
GET http://localhost:8080/products?categoryId=5

### GET Product by ID
GET http://localhost:8080/products/17

### Create a new User
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@email.com",
  "password": "87654321"
}

### Update a User
PUT http://localhost:8080/users/25
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@email.com",
  "password": "P@ssw0rd123"
}