spring.application.name=Store-Api

stripe.apiUrl=https://api.stripe.com
stripe.enabled=true
stripe.timeout=1000
stripe.supported-currencies=USD,EUR,GBP

spring.datasource.url=jdbc:mysql://localhost:3306/storeDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root