spring.application.name=Store-Api

spring.datasource.url=jdbc:mysql://localhost:3306/storeDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true